# Generated by Django 4.2.2 on 2023-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('hold', 'Hold')], default=False),
        ),
    ]
