# Generated by Django 4.2.2 on 2023-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_tasks_priority_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Hold', 'Hold')], default=False),
        ),
    ]
