# Generated by Django 4.2.2 on 2023-10-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tasks_description_alter_tasks_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='user',
            new_name='created_by',
        ),
    ]
